### ISSUE TITLE
Rerender feedstock seems to give files extra permisions

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-smithy#424]
So I ran into this while rendering the feedstock for ase it seems that my files have a lot more permissions than expected.
See conda-forge/ase-feedstock#2
For my workflow I:
1. forked the repo
1. created a local clone
1. ran conda smithy rerender --commit
1. added my api tokens as needed
1. pushed to my fork
my conda environment
```python
# packages in environment at /home/christopher/mc:
#
Using Anaconda API: https://api.anaconda.org
attrs                     16.3.0                    <pip>
autobahn                  0.17.1                    <pip>
cffi                      1.9.1                     <pip>
click                     6.6                       <pip>
conda-build               2.0.8                    py27_0  
anaconda-client           1.5.1                    py27_0    conda-forge
clyent                    1.2.1                    py27_0    conda-forge
conda                     4.1.12                   py27_0    conda-forge
conda-build-all           1.0.1                    py27_1    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-smithy              1.7.0                    py27_0    conda-forge
contextlib2               0.5.3                    py27_0    conda-forge
filelock                  2.0.6                    py27_0    conda-forge
funcsigs                  1.0.2                    py27_0    conda-forge
gitdb                     0.6.4                    py27_0    conda-forge
gitpython                 2.0.8                    py27_1    conda-forge
jinja2                    2.8                      py27_1    conda-forge
markupsafe                0.23                     py27_0    conda-forge
mock                      2.0.0                    py27_0    conda-forge
patchelf                  0.9                           1    conda-forge
pbr                       1.10.0                   py27_0    conda-forge
pkginfo                   1.2.1                    py27_0    conda-forge
pygithub                  1.29                     py27_0    conda-forge
python-dateutil           2.6.0                    py27_0    conda-forge
pytz                      2016.10                  py27_0    conda-forge
ruamel.ordereddict        0.4.6                    py27_0    conda-forge
ruamel.yaml               0.11.11                  py27_1    conda-forge
six                       1.10.0                   py27_1    conda-forge
smmap                     0.9.0                    py27_0    conda-forge
sqlite                    3.13.0                        0    conda-forge
constantly                15.1.0                    <pip>
cryptography              1.7.1                     <pip>
diffpy.pdfgetx-1.0-r2152  20130314                  <pip>
enum34                    1.1.6                     <pip>
hkdf                      0.0.3                     <pip>
humanize                  0.5.1                     <pip>
idna                      2.2                       <pip>
incremental               16.10.1                   <pip>
ipaddress                 1.0.17                    <pip>
pymongo                   3.2.2                    py27_0    lightsource2
magic-wormhole            0.9.1                     <pip>
openssl                   1.0.2g                        0  
pip                       8.1.1                    py27_1  
pip                       9.0.1                     <pip>
pyasn1                    0.1.9                     <pip>
pyasn1-modules            0.0.8                     <pip>
pycosat                   0.6.1                    py27_0  
pycparser                 2.17                      <pip>
pycrypto                  2.6.1                    py27_0  
PyNaCl                    1.0.1                     <pip>
pyOpenSSL                 16.2.0                    <pip>
python                    2.7.12                        1  
pyyaml                    3.11                     py27_1  
readline                  6.2                           2  
requests                  2.9.1                    py27_0  
ruamel_yaml               0.11.7                   py27_0  
service-identity          16.0.0                    <pip>
setuptools                20.3                     py27_0  
six                       1.10.0                    <pip>
spake2                    0.7                       <pip>
tk                        8.5.18                        0  
tqdm                      4.10.0                    <pip>
Twisted                   16.6.0                    <pip>
txaio                     2.6.0                     <pip>
wheel                     0.29.0                   py27_0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         0  
zope.interface            4.3.3                     <pip>
```
I also recently checked out the master branch of the main repo for ase and got the following permissions for the files.
```sh
total 42
drwxrwxrwx 1 christopher christopher 4096 Jan  9 20:42 .
drwxrwxrwx 1 christopher christopher 4096 Jan  5 19:39 ..
-rwxrwxrwx 1 christopher christopher 3446 Jan  9 20:42 appveyor.yml
-rwxrwxrwx 1 christopher christopher  438 Jan  9 20:42 circle.yml
drwxrwxrwx 1 christopher christopher    0 Jan  5 10:58 ci_support
-rwxrwxrwx 1 christopher christopher  826 Jan  5 10:57 conda-forge.yml
drwxrwxrwx 1 christopher christopher 4096 Jan  9 20:43 .git
-rwxrwxrwx 1 christopher christopher   78 Jan  9 20:42 .gitattributes
-rwxrwxrwx 1 christopher christopher   23 Jan  9 20:42 .gitignore
drwxrwxrwx 1 christopher christopher 4096 Jan  5 11:03 .idea
-rwxrwxrwx 1 christopher christopher 1497 Jan  9 20:42 LICENSE
-rwxrwxrwx 1 christopher christopher 4623 Jan  9 20:42 README.md
drwxrwxrwx 1 christopher christopher    0 Jan  9 20:42 recipe
-rwxrwxrwx 1 christopher christopher 1797 Jan  9 20:42 .travis.yml
```

Any insight would be greatly appreciated.

**Comment by jakirkham** [comment]
Thanks @CJ-Wright . What platform were using? Also can you replace the env info from what you find by running `conda list -n root`?

**Comment by jakirkham** [comment]
That's strange. Why do group members and everyone have write permissions?

**Comment by jakirkham** [comment]
Didn't you have a similar issue to this @jjhelmus ?

**Comment by CJ-Wright** [comment]
I am on ubuntu 16.04. I am not certain about the permissions, it was newly cloned.
The conda list has been updated

**Comment by CJ-Wright** [comment]
Ah, could this be due to the drive being ntfs? (It is shared with a windows partition)

**Comment by jakirkham** [comment]
Yep, that sounds like a potential issue. I'd do a quick search and see if you can find some info about how Linux needs to be configured to correctly read NTFS. The worrisome thing is that basically everything has 777 permissions set. This may take some tweaking both on the Windows and the Linux side to get it sorted.

**Comment by grlee77** [comment]
This occurred for me as well a while back, also while working on linux with an NTFS mounted drive (see:  https://github.com/conda-forge/pywavelets-feedstock/pull/7, but I don't think we ever did track down exactly why this occurs)

**Comment by jakirkham** [comment]
I think it ceased to be reproducible, correct? Or has it resurfaced for you since.

xref: https://github.com/conda-forge/conda-smithy/issues/365

**Comment by jakirkham** [comment]
Suppose we could just set everything to not have executable permission initially. We initially considered such a change, but we dismissed as we wanted file permissions to come from the files directly. However, at this juncture we already have to explicitly set executable permissions in `git`'s index to be able to have correct file permissions on Windows. So can't see how setting everything to not have executable permissions from the get go will be bad for us. Will try to resurrect that PR.

xref: https://github.com/conda-forge/conda-smithy/pull/379

**Comment by jakirkham** [comment]
Could you guys please take a look at PR ( https://github.com/conda-forge/conda-smithy/pull/379 ) and try it out if possible. Would like to know if that is a reasonable fix.

**Comment by jjhelmus** [comment]
> Didn't you have a similar issue to this @jjhelmus ?

Yes, but I have not run into this for quite some time so whatever was causing my issue seems to have solved itself.

**Comment by jakirkham** [comment]
Glad to hear it hasn't resurfaced. Unfortunate that we still don't know the cause.

**Comment by jakirkham** [comment]
Honestly file system permissions seem to be a delicate thing. The only way we have been able to ensure they will be correct is using `git`'s index to record the right permissions. We still try to set them correctly on the system as well, but in cases like this I don't know if they are respected. It easier to just ensure the index is an accurate reflection of what the permissions should be and avoid reliance on disk permissions.

**Comment by jakirkham** [comment]
Has anyone had a chance to try PR ( https://github.com/conda-forge/conda-smithy/pull/379 )? Would really like to know if that helps solve the problem.

Am looking to cut a release ideally tomorrow so that we can start handling many of the problems already fixed in `master` (e.g. enabling CircleCI PR builds, bumping the Travis CI image, dropping Python 3.4), which are badly in need. Would like to include this in that release, but would like at least someone with this issue to try it first. Otherwise I might have to leave that fix out.

Could you please take a look @CJ-Wright as you have a current reproducing environment? Thanks in advance.

**Comment by CJ-Wright** [comment]
I think this all boils down to my windows ntfs mount doing silly stuff with the permissions. I tried to run this an it did not fix the permissions. I don't know if this works for other people or not. I'm planning on moving my development folder to a non ntfs mounted drive to get rid of this problem for good.

**Comment by jakirkham** [comment]
So this wouldn't fix the permissions on the file system as there is something off about the Linux configuration used with NTFS. Though it might be possible to fix that based on this [old answer]( http://askubuntu.com/a/74851 ).

That all being said, the re-rendering should have the right permissions in `git`'s index. If that is not the case, I would be very interested to know. Could you please try re-rendering with the PR on the NTFS drive with `conda smithy rerender` and then run `git diff --cached`? Please share the diff it gives you.

> Update: I moved a trial directory to the pure linux drive and re-ran the rerender and it seems to have properly changed my permissions. So I just need to move everything over and I should be ok.

Could you explain how this was done a bit more? There still appears to be files with executable permissions (e.g. `README.md`). Is `conda-smithy` installed on the NTFS drive (or partition) somewhere for instance? Though I'm less concerned with the on disk permissions than the ones recorded in `git` ATM.

While it is totally up to you what sort of workflow you want to use with `conda-smithy` on your setup, this is not the first time someone has raised an issue like the one you have and I doubt it will be the last. I can only imagine how frustrating it is, especially for newer users, to run into issues with something like this. For this reason, I think it would be nice for us to have a reasonable fail safe in `conda-smithy` to still create re-renderings with correct permissions regardless of the state of the users file system, OS, or other configurations. This is especially important given how ubiquitous re-renderings are in conda-forge. In this regard, I greatly appreciate your help in trying fixes and workarounds.

**Comment by CJ-Wright** [comment]
Here is the diff
```
diff --git a/.gitattributes b/.gitattributes
new file mode 100755
index 0000000..288029d
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1,5 @@
+* text=auto
+
+meta.yaml text eol=lf
+build.sh text eol=lf
+bld.bat text eol=crlf
diff --git a/.gitignore b/.gitignore
old mode 100644
new mode 100755
diff --git a/.travis.yml b/.travis.yml
old mode 100644
new mode 100755
index 5a91073..4acf62c
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,6 +10,7 @@ env:
   matrix:
     
     - CONDA_PY=35
+    - CONDA_PY=36
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "CVCmZYTy2n2SbIQbuTfZkh1MvAGy4EyKm/WIniviQJIfagvSMVqy7C3tu+P/ZE55ez/MiFnrnUDH86INs8MoqR+5wPWqN2GMc01P1b0t6lvKIh7+d/6sFaiuietRo2JJSj4j8lYKqyfmHe5ZZZ0Wvw7kvfDt/FbAdcWWTRzthmZ2RCjRVchiVkoJIhCiS6d4RRx1I5vCUJpxjMJrj6jgCfEIh24CO9iEAOWmPntCg2lpqQ4Nac941YWxYg8XXsJQ9k26pttG2i4uPmO7fmcvYkTOx765PDYiAYVw/gFQ9twT4xp5LoYvM/4Ni6Q/73/w5j7GegPeaSgTJ11HshmkuVO7qrKNB3iImASXDcsYQkA4zdN5COyEcDfwYok1PzcDoLI1qnIwtAV9r6hV/TOE917blwIPGQvWpDh3RmNrgf2R96c4dW84Irdhfc0FCw+UjZF/edxxqS/g3ZmEDnTPZT+Us0iTIWNSkxSHadsTG4Zs6inLACcl4/jqhdpb4O4C8V6iEmX763h21AnU+2AwkoXs/diWv4ZlNNGDEFRauZLOOVslPZl0j8nPti+VrFFhbmod6CNxfiR/BLM5KX0H+0yiZMrPHyhsJMa14Io8EJNiM+P/80pIP9tfrXIPXuc2e94S0oompnTVV1bFk4gQxeikAg9sqGz0+4bTWS/j36U="
diff --git a/LICENSE b/LICENSE
old mode 100644
new mode 100755
diff --git a/README.md b/README.md
old mode 100644
new mode 100755
index 7108c22..ba22187
--- a/README.md
+++ b/README.md
@@ -13,6 +13,18 @@ A tool for automatically building Sphinx docs on Travis CI, and deploying
 them to GitHub pages.
 
 
+Current build status
+====================
+
+Linux: [![Circle CI](https://circleci.com/gh/conda-forge/doctr-feedstock.svg?style=shield)](https://circleci.com/gh/conda-forge/doctr-feedstock)
+OSX: [![TravisCI](https://travis-ci.org/conda-forge/doctr-feedstock.svg?branch=master)](https://travis-ci.org/conda-forge/doctr-feedstock)
+Windows: [![AppVeyor](https://ci.appveyor.com/api/projects/status/github/conda-forge/doctr-feedstock?svg=True)](https://ci.appveyor.com/project/conda-forge/doctr-feedstock/branch/master)
+
+Current release info
+====================
+Version: [![Anaconda-Server Badge](https://anaconda.org/conda-forge/doctr/badges/version.svg)](https://anaconda.org/conda-forge/doctr)
```

**Comment by CJ-Wright** [comment]
diff --git a/.gitattributes b/.gitattributes
new file mode 100755
index 0000000..288029d
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1,5 @@
+* text=auto
+
+meta.yaml text eol=lf
+build.sh text eol=lf
+bld.bat text eol=crlf
diff --git a/.gitignore b/.gitignore
old mode 100644
new mode 100755
diff --git a/.travis.yml b/.travis.yml
old mode 100644
new mode 100755
index 5a91073..4acf62c
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,6 +10,7 @@ env:
   matrix:
     
     - CONDA_PY=35
+    - CONDA_PY=36
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "CVCmZYTy2n2SbIQbuTfZkh1MvAGy4EyKm/WIniviQJIfagvSMVqy7C3tu+P/ZE55ez/MiFnrnUDH86INs8MoqR+5wPWqN2GMc01P1b0t6lvKIh7+d/6sFaiuietRo2JJSj4j8lYKqyfmHe5ZZZ0Wvw7kvfDt/FbAdcWWTRzthmZ2RCjRVchiVkoJIhCiS6d4RRx1I5vCUJpxjMJrj6jgCfEIh24CO9iEAOWmPntCg2lpqQ4Nac941YWxYg8XXsJQ9k26pttG2i4uPmO7fmcvYkTOx765PDYiAYVw/gFQ9twT4xp5LoYvM/4Ni6Q/73/w5j7GegPeaSgTJ11HshmkuVO7qrKNB3iImASXDcsYQkA4zdN5COyEcDfwYok1PzcDoLI1qnIwtAV9r6hV/TOE917blwIPGQvWpDh3RmNrgf2R96c4dW84Irdhfc0FCw+UjZF/edxxqS/g3ZmEDnTPZT+Us0iTIWNSkxSHadsTG4Zs6inLACcl4/jqhdpb4O4C8V6iEmX763h21AnU+2AwkoXs/diWv4ZlNNGDEFRauZLOOVslPZl0j8nPti+VrFFhbmod6CNxfiR/BLM5KX0H+0yiZMrPHyhsJMa14Io8EJNiM+P/80pIP9tfrXIPXuc2e94S0oompnTVV1bFk4gQxeikAg9sqGz0+4bTWS/j36U="
diff --git a/LICENSE b/LICENSE
old mode 100644
new mode 100755
diff --git a/README.md b/README.md
old mode 100644
new mode 100755
index 7108c22..ba22187
--- a/README.md
+++ b/README.md
@@ -13,6 +13,18 @@ A tool for automatically building Sphinx docs on Travis CI, and deploying
 them to GitHub pages.
 
 
+Current build status
+====================
+
+Linux: [![Circle CI](https://circleci.com/gh/conda-forge/doctr-feedstock.svg?style=shield)](https://circleci.com/gh/conda-forge/doctr-feedstock)
+OSX: [![TravisCI](https://travis-ci.org/conda-forge/doctr-feedstock.svg?branch=master)](https://travis-ci.org/conda-forge/doctr-feedstock)
+Windows: [![AppVeyor](https://ci.appveyor.com/api/projects/status/github/conda-forge/doctr-feedstock?svg=True)](https://ci.appveyor.com/project/conda-forge/doctr-feedstock/branch/master)
+
+Current release info
+====================
+Version: [![Anaconda-Server Badge](https://anaconda.org/conda-forge/doctr/badges/version.svg)](https://anaconda.org/conda-forge/doctr)

**Comment by jakirkham** [comment]
Hmm...that's surprising. Would have figured git's index would get away from this NTFS mess unscathed. Appears that is not the case. Not entirely sure what else we can do then. 😕

**Comment by jakirkham** [comment]
Are you still encountering this issue @CJ-Wright?

**Comment by CJ-Wright** [comment]
No but only because I have moved off NTFS
